import React from "react";
import { makeStyles } from "@material-ui/core/styles";
import AppBar from "@material-ui/core/AppBar";
import List from "@material-ui/core/List";
import ListItem from "@material-ui/core/ListItem";
import ListItemAvatar from "@material-ui/core/ListItemAvatar";
import ListItemText from "@material-ui/core/ListItemText";
// import ListSubheader from "@material-ui/core/ListSubheader";
import Avatar from "@material-ui/core/Avatar";
import Button from "@material-ui/core/Button";
import Icon from "@material-ui/core/Icon";
import Grid from "@material-ui/core/Grid";
import { CenterInput } from "./authorization";



const messages = [
  {
    id: 1,
    login: "Brad",
    message: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    photo: "/static/images/avatar/5.jpg"
  },
  {
    id: 2,
    login: "Mike",
    message: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    photo: "/static/images/avatar/1.jpg"
  },
  {
    id: 3,
    login: "Brad",
    message: "I am try out this new BBQ recipe, I think this might be amazing",
    photo: "/static/images/avatar/2.jpg"
  },
  {
    id: 4,
    login: "Milene",
    message: "I have the tickets to the ReactConf for this year.",
    photo: "/static/images/avatar/3.jpg"
  },
  {
    id: 5,
    login: "Steve",
    message: "My appointment for the doctor was rescheduled for next Saturday.",
    photo: "/static/images/avatar/4.jpg"
  },
  {
    id: 6,
    login: "Zoe",
    message: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    photo: "/static/images/avatar/5.jpg"
  },
  {
    id: 7,
    login: "Mike02815",
    message: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    photo: "/static/images/avatar/1.jpg"
  }
];

const useStyles = makeStyles(theme => ({
  appBar: {
    background: "#fff",
    color: "#000",
    top: "auto",
    bottom: 0
  },
  list: {
    marginBottom: theme.spacing(2),
    paddingBottom: 70
  },
  subheader: {
    backgroundColor: theme.palette.background.paper
  },
  grow: {
    flexGrow: 1
  },
  button: {
    marginTop: 25
  }
}));

export default function BottomAppBar() {
  const classes = useStyles();


  return (
    <React.Fragment>
      <List className={classes.list}>
        {messages.map(({ id, login, message, photo }) => (
          <React.Fragment key={id}>
            {/* {id === 1 && (
              <ListSubheader className={classes.subheader}>Today</ListSubheader>
            )}
            {id === 3 && (
              <ListSubheader className={classes.subheader}>
                Yesterday
              </ListSubheader>
            )} */}
            <ListItem button>
              <ListItemAvatar>
                <Avatar alt="Photo" src={photo} />
              </ListItemAvatar>
              <ListItemText primary={login} secondary={message} />
            </ListItem>
          </React.Fragment>
        ))}
      </List>

      <AppBar position="fixed" className={classes.appBar}>
        <Grid container spacing={1}>
          <Grid item xs={11}>
            <CenterInput placeholder="Введите сообщение" />
          </Grid>
          <Grid item xs={1}>
            <Button variant="contained" color="#fff" className={classes.button}>
              <Icon>send</Icon>
            </Button>
          </Grid>
        </Grid>
      </AppBar>
    </React.Fragment>
  );
}
